### ISSUE TITLE
Not strictly equal to mathematical value of π

### ISSUE THREAD

**Issue by RReverser** [const-io/pi#1]
First of all, thanks for the useful library collection! We've built our entire stack of a big e-commerce application using just modules from this organization.

However, our users noticed a minor issue: the value of PI provided by this library is `3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679`, while the real mathematical value of π has slightly more digits.

**Comment by kgryte** [comment]
@RReverser Thanks for the note. And yes, the value exported by this module is not equal to `PI`. In a perfect world, we would have infinite precision and could represent `PI` exactly. But, in fact, the exported value is truncated due to finite precision => `3.141592653589793`, which is the same value as the built-in `Math.PI`. And, in general, this should be the value anytime `PI` is stored as a IEEE 754 double-precision floating-point number.

Aside: how did a user notice the finite precision of `PI` and how was s/he affected?

**Comment by kgryte** [comment]
@RReverser Actually, found the Twitter feed and see that you are just trolling. Closing.
