### ISSUE TITLE
Why should this be used over Math.PI?

### ISSUE THREAD

**Issue by ferno** [const-io/pi#4]
I'm not aware of a single JavaScript environment which doesn't provide the constant `Math.PI`. What is the purpose of this module?

**Comment by kgryte** [comment]
Someone may

* prefer explicit over implicit dependencies.
* prefer dependency injection over Globals.
* want better ability to mock environments; e.g., by intercepting `require`.
* want a similar design to, say, Boost, where constants are deps, not globals.

All variants on the same theme.

History: was part of a larger project beyond this repo/org which has evolved since this repo was created.
